name: terraform-apply-dev

on:
  push:
    branches:
      - main
    paths:
      - 'live/**'
      - 'modules/**'
      - '.github/workflows/**'

jobs:
  apply-dev:
    uses: ./.github/workflows/_terraform-reusable.yml
    with:
      environment: dev
      working_directory: live/dev/app
      aws_region: ap-northeast-2
      aws_role_arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/GitHubActionsTerraformDevRole
      action: apply
